apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlflow-workflow-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: create-parent-run
            template: create-parent-run
            outputs:
              parameters:
                - name: parent-run-id
                  valueFrom:
                    path: /tmp/parent_run_id.txt

          - name: preprocess
            template: mlflow
            arguments:
              parameters:
                - name: entry_point
                  value: preprocess
                - name: parent_run_id
                  value: "{{tasks.create-parent-run.outputs.parameters.parent-run-id}}"
            dependencies: [create-parent-run]

          - name: train
            template: mlflow
            arguments:
              parameters:
                - name: entry_point
                  value: train
                - name: parent_run_id
                  value: "{{tasks.preprocess.outputs.parameters.parent_run_id}}"
            dependencies: [preprocess]

          - name: evaluate
            template: mlflow
            arguments:
              parameters:
                - name: entry_point
                  value: evaluate
                - name: parent_run_id
                  value: "{{tasks.train.outputs.parameters.parent_run_id}}"
            dependencies: [train]

          - name: deploy
            template: mlflow
            arguments:
              parameters:
                - name: entry_point
                  value: deploy
                - name: parent_run_id
                  value: "{{tasks.evaluate.outputs.parameters.parent_run_id}}"
            dependencies: [evaluate]

    - name: create-parent-run
      script:
        image: <your-dockerhub-username>/custom-mlflow-conda:latest
        command: ["conda", "run", "--no-capture-output", "-n", "mlflow-env", "python", "create_parent_run.py"]
        volumeMounts:
          - name: mlflow-project
            mountPath: /mnt/mlflow-project
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
        outputs:
          parameters:
            - name: parent-run-id
              valueFrom:
                path: /tmp/parent_run_id.txt

    - name: mlflow
      inputs:
        parameters:
          - name: entry_point
          - name: parent_run_id
      container:
        image: marcy326/mlflow-conda:py3.11
        command: ["conda", "run", "--no-capture-output", "-n", "mlflow-env", "mlflow", "run", "https://github.com/marcy326/mlflow-argo.git"]
        args: ["--entry-point", "{{inputs.parameters.entry_point}}", "-P", "parent_run_id={{inputs.parameters.parent_run_id}}"]
        volumeMounts:
          - name: mlflow-project
            mountPath: /mnt/mlflow-project
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"

    volumes:
      - name: mlflow-project
        persistentVolumeClaim:
          claimName: mlflow-project-pvc
